name: Say hello

on:
  push:
    branches:
      - main
      - practice
jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo 'Hola Gerardo'
