name: Say hello

on:
  push:
    branches:
      - main
      - practice
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message
        run: |
          echo 'Hola Gerardo'
      - name: Dime la fecha
        run: date
      - run: ls -l
