name: Deployment Pipeline

on:
  push:
    branches: [practice]
  pull_request:
    branches: [practice]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm ci
          npm update webpack --no-audit --no-fund --no-optional
          npx browserslist@latest --update-db --no-audit --no-fund --no-optional
          npm install --save-dev cross-env
          npm install cypress --save-dev
      - name: Lint
        run: npm run eslint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm ci
          npm update webpack --no-audit --no-fund --no-optional
          npx browserslist@latest --update-db --no-audit --no-fund --no-optional
          npm install --save-dev cross-env
          npm install cypress --save-dev
      - name: Build project
        run: NODE_OPTIONS=--openssl-legacy-provider npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm ci
          npm update webpack --no-audit --no-fund --no-optional
          npx browserslist@latest --update-db --no-audit --no-fund --no-optional
          npm install --save-dev cross-env
          npm install cypress --save-dev
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Test
        run: npm test

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm ci
          npm update webpack --no-audit --no-fund --no-optional
          npx browserslist@latest --update-db --no-audit --no-fund --no-optional
          npm install --save-dev cross-env
          npm install cypress --save-dev
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm ci
          npm update webpack --no-audit --no-fund --no-optional
          npx browserslist@latest --update-db --no-audit --no-fund --no-optional
          npm install --save-dev cross-env
          npm install cypress --save-dev
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: E2E tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start-test
          wait-on: http://localhost:5000
