name: Deployment Pipeline

on:
  push:
    branches:
      - practice

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm install
          npm update webpack
          npx browserslist@latest --update-db
      - name: Lint
        run: npm run eslint
