name: Deployment Pipeline

on:
  push:
    branches:
      - practice

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund --no-optional
          npm update webpack
          npx browserslist@latest --update-db
      - name: Set legacy OpenSSL provider
        run: echo "NODE_OPTIONS=--openssl-legacy-provider" >> $GITHUB_ENV
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
